In [22]:
import pandas as pd
import numpy as np
df=pd.read_csv("C:\\Users\\Indrajit\\Documents\\Employee_Data.csv")
df


Department  WorkedHours  Certification  YearsExperience  Salary
0   Development         2300              0              1.1   39343
1       Testing         2100              1              1.3   46205
2   Development         2104              2              1.5   37731
3   UX Designer         1200              1              2.0   43525
4       Testing         1254              2              2.2   39891
5   UX Designer         1236              1              2.9   56642
6   Development         1452              2              3.0   60150
7       Testing         1789              1              3.2   54445
8   UX Designer         1645              1              3.2   64445
9   UX Designer         1258              0              3.7   57189
10      Testing         1478              3              3.9   63218
11  Development         1257              2              4.0   55794
12  Development         1596              1              4.0   56957
13      Testing         1256              2              4.1   57081
14  UX Designer         1489              3              4.5   61111
15  Development         1236              3              4.9   67938
16      Testing         2311              2              5.1   66029
17  UX Designer         2245              3              5.3   83088
18  Development         2365              1              5.9   81363
19  Development         1500              3              6.0   93940
20      Testing         1456              2              6.8   91738
21      Testing         1760              1              7.1   98273
22  UX Designer         2400              4              7.9  101302
23  Development         2148              3              8.2  113812
24  UX Designer         1450              2              8.7  109431
25  UX Designer         1000              4              9.0  105582
26      Testing         1540              3              9.5  116969
27  Development         1500              2              9.6  112635
28      Testing         3000              4             10.3  122391
29  UX Designer         2100              3             10.5  121872

In [27]:
x=df.iloc[:,0:4].values
x

array([['Development', 2300, 0, 1.1],
       ['Testing', 2100, 1, 1.3],
       ['Development', 2104, 2, 1.5],
       ['UX Designer', 1200, 1, 2.0],
       ['Testing', 1254, 2, 2.2],
       ['UX Designer', 1236, 1, 2.9],
       ['Development', 1452, 2, 3.0],
       ['Testing', 1789, 1, 3.2],
       ['UX Designer', 1645, 1, 3.2],
       ['UX Designer', 1258, 0, 3.7],
       ['Testing', 1478, 3, 3.9],
       ['Development', 1257, 2, 4.0],
       ['Development', 1596, 1, 4.0],
       ['Testing', 1256, 2, 4.1],
       ['UX Designer', 1489, 3, 4.5],
       ['Development', 1236, 3, 4.9],
       ['Testing', 2311, 2, 5.1],
       ['UX Designer', 2245, 3, 5.3],
       ['Development', 2365, 1, 5.9],
       ['Development', 1500, 3, 6.0],
       ['Testing', 1456, 2, 6.8],
       ['Testing', 1760, 1, 7.1],
       ['UX Designer', 2400, 4, 7.9],
       ['Development', 2148, 3, 8.2],
       ['UX Designer', 1450, 2, 8.7],
       ['UX Designer', 1000, 4, 9.0],
       ['Testing', 1540, 3, 9.5],
       ['D

In [30]:
from sklearn.preprocessing import LabelEncoder
labelencoder_x=LabelEncoder()
x[:,0]=labelencoder_x.fit_transform(x[:,0])
x

array([[0, 2300, 0, 1.1],
       [1, 2100, 1, 1.3],
       [0, 2104, 2, 1.5],
       [2, 1200, 1, 2.0],
       [1, 1254, 2, 2.2],
       [2, 1236, 1, 2.9],
       [0, 1452, 2, 3.0],
       [1, 1789, 1, 3.2],
       [2, 1645, 1, 3.2],
       [2, 1258, 0, 3.7],
       [1, 1478, 3, 3.9],
       [0, 1257, 2, 4.0],
       [0, 1596, 1, 4.0],
       [1, 1256, 2, 4.1],
       [2, 1489, 3, 4.5],
       [0, 1236, 3, 4.9],
       [1, 2311, 2, 5.1],
       [2, 2245, 3, 5.3],
       [0, 2365, 1, 5.9],
       [0, 1500, 3, 6.0],
       [1, 1456, 2, 6.8],
       [1, 1760, 1, 7.1],
       [2, 2400, 4, 7.9],
       [0, 2148, 3, 8.2],
       [2, 1450, 2, 8.7],
       [2, 1000, 4, 9.0],
       [1, 1540, 3, 9.5],
       [0, 1500, 2, 9.6],
       [1, 3000, 4, 10.3],
       [2, 2100, 3, 10.5]], dtype=object)

In [31]:
from sklearn.preprocessing import StandardScaler

In [32]:
sc=StandardScaler()

In [34]:
x=sc.fit_transform(x)
x

array([[-1.22474487,  1.23991938, -1.89010336, -1.51005294],
       [ 0.        ,  0.81661831, -0.97553722, -1.43837321],
       [-1.22474487,  0.82508433, -0.06097108, -1.36669348],
       [ 1.22474487, -1.0882365 , -0.97553722, -1.18749416],
       [ 0.        , -0.97394521, -0.06097108, -1.11581443],
       [ 1.22474487, -1.01204231, -0.97553722, -0.86493538],
       [-1.22474487, -0.55487715, -0.06097108, -0.82909552],
       [ 0.        ,  0.15838515, -0.97553722, -0.75741579],
       [ 1.22474487, -0.14639162, -0.97553722, -0.75741579],
       [ 1.22474487, -0.96547919, -1.89010336, -0.57821647],
       [ 0.        , -0.49984801,  0.85359507, -0.50653674],
       [-1.22474487, -0.96759569, -0.06097108, -0.47069688],
       [-1.22474487, -0.25010038, -0.97553722, -0.47069688],
       [ 0.        , -0.9697122 , -0.06097108, -0.43485702],
       [ 1.22474487, -0.47656645,  0.85359507, -0.29149756],
       [-1.22474487, -1.01204231,  0.85359507, -0.1481381 ],
       [ 0.        ,  1.

In [35]:
y=df.iloc[:,4].values
y

array([ 39343,  46205,  37731,  43525,  39891,  56642,  60150,  54445,
        64445,  57189,  63218,  55794,  56957,  57081,  61111,  67938,
        66029,  83088,  81363,  93940,  91738,  98273, 101302, 113812,
       109431, 105582, 116969, 112635, 122391, 121872], dtype=int64)

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.2,random_state=0)


In [39]:
x_train.shape

(24, 4)

In [40]:
x_test.shape

(6, 4)

In [43]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [45]:
y_pred=lr.predict(x_test)
y_pred

array([ 43409.053136  , 128099.28591441,  63164.26677545,  62469.69286371,
       114088.73683056, 105916.16311573])

In [46]:
y_test

array([ 37731, 122391,  57081,  63218, 116969, 109431], dtype=int64)

In [48]:
from sklearn.metrics import mean_absolute_error
mae=mean_absolute_error(y_pred,y_test)
mae

4102.1688359765585